databases:
  - name: edi
    plan: free
    databaseName: edidb
    user: postgres

services:
  - type: web
    plan: free
    name: edi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn edi.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgresql://edimar_user:c8F9EWnW5UH9t67RF6XTXS7tm1btqhsv@dpg-d5rsnd718n1s73cvs310-a/edimar
        fromDatabase:
          name: edidb
          property: connectionString
      - key: "django-insecure-u@&cyz_*ebvy*6g1$w)264zisbpq4zdj+32t*6y)4#5!5h=u^4"
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
